# Generated by Django 3.2.5 on 2021-11-07 16:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bloodbank', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Donor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Donor_Name', models.CharField(max_length=69)),
                ('Donor_Email', models.EmailField(max_length=254)),
                ('Donor_Phone', models.CharField(max_length=15, null=True)),
                ('Donor_District', models.CharField(max_length=15, null=True)),
                ('Donor_Area', models.CharField(max_length=15, null=True)),
                ('Donor_Postalcode', models.IntegerField()),
                ('Date_Of_Donation', models.DateField()),
                ('Donor_Bloodhroup', models.CharField(max_length=5, null=True)),
                ('Blood_Bank_Name', models.CharField(max_length=70, null=True)),
            ],
        ),
    ]
